### ISSUE TITLE
Item ID's

### ISSUE THREAD

**Issue by Assasinowy** [storm345dev/ucars#21]
I have an issue with slabs, On 1.12 relase it's not possible to add slabs as boosters nor jump blocks, If I could get a list of working block names it would be very helpful

**Comment by Jakllp** [comment]
Hey, this repo is fairly dead.  
I maintain an improved fork of the plugin (just go to my github profile and then ucars)  
Can you try again with a 1.12 build from over there - and if the problem persists add an issue over there?

(the github-releases are called 1.13+ but there's a 1.12-jar in the assets)
